version: '3'
services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    user: root
    volumes:
    - ./data/jenkins_home:/var/jenkins_home
    ports:
    - 8080:8080
    - 50000:50000
